// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinmple.Data;

#nullable disable

namespace Sinmple.Migrations
{
    [DbContext(typeof(SinmpleContext))]
    [Migration("20231116205136_pruebaMigration")]
    partial class pruebaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sinmple.Models.Almacen", b =>
                {
                    b.Property<string>("IdAlmacen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlmacen");

                    b.ToTable("Almacen");
                });

            modelBuilder.Entity("Sinmple.Models.Cuenta", b =>
                {
                    b.Property<string>("IdCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioNavigationIdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdUsuarioNavigationIdUsuario");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("Sinmple.Models.Lote", b =>
                {
                    b.Property<string>("IdLote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("FechaElaboracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaVencimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProductoNavigationIdProducto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioNavigationIdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreLote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLote");

                    b.HasIndex("IdProductoNavigationIdProducto");

                    b.HasIndex("IdUsuarioNavigationIdUsuario");

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("Sinmple.Models.MovimientosInventario", b =>
                {
                    b.Property<string>("IdMovimiento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdLoteFk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdLoteFkNavigationIdLote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdLoteFkNavigationIdLote");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Sinmple.Models.Producto", b =>
                {
                    b.Property<string>("IdProducto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Sinmple.Models.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Sinmple.Models.Cuenta", b =>
                {
                    b.HasOne("Sinmple.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Cuenta")
                        .HasForeignKey("IdUsuarioNavigationIdUsuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Sinmple.Models.Lote", b =>
                {
                    b.HasOne("Sinmple.Models.Producto", "IdProductoNavigation")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProductoNavigationIdProducto");

                    b.HasOne("Sinmple.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Lotes")
                        .HasForeignKey("IdUsuarioNavigationIdUsuario");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Sinmple.Models.MovimientosInventario", b =>
                {
                    b.HasOne("Sinmple.Models.Lote", "IdLoteFkNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdLoteFkNavigationIdLote");

                    b.Navigation("IdLoteFkNavigation");
                });

            modelBuilder.Entity("Sinmple.Models.Lote", b =>
                {
                    b.Navigation("MovimientoInventarios");
                });

            modelBuilder.Entity("Sinmple.Models.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Sinmple.Models.Usuario", b =>
                {
                    b.Navigation("Cuenta");

                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
