// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinmple.Data;

#nullable disable

namespace Sinmple.Migrations
{
    [DbContext(typeof(SinmpleContext))]
    partial class SinmpleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sinmple.Models.Almacen", b =>
                {
<<<<<<< HEAD
                    b.Property<string>("IdAlmacen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlmacen");
=======
                    b.Property<int>("Id_almacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_almacen"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_almacen");
>>>>>>> 7f5891263b969f04d49c94ffaf374eeea2c2c7aa

                    b.ToTable("Almacen");
                });

            modelBuilder.Entity("Sinmple.Models.Cuenta", b =>
                {
<<<<<<< HEAD
                    b.Property<string>("IdCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioNavigationIdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdUsuarioNavigationIdUsuario");
=======
                    b.Property<int>("Id_cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_cuenta"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_cuenta");
>>>>>>> 7f5891263b969f04d49c94ffaf374eeea2c2c7aa

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("Sinmple.Models.Lote", b =>
                {
<<<<<<< HEAD
                    b.Property<string>("IdLote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("FechaElaboracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaVencimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProductoNavigationIdProducto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUsuarioNavigationIdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreLote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLote");

                    b.HasIndex("IdProductoNavigationIdProducto");

                    b.HasIndex("IdUsuarioNavigationIdUsuario");
=======
                    b.Property<int>("Id_lote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_lote"));

                    b.Property<int>("Almacen_id")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaElaboracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_lote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Productos_id")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("Id_lote");
>>>>>>> 7f5891263b969f04d49c94ffaf374eeea2c2c7aa

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("Sinmple.Models.MovimientosInventario", b =>
                {
<<<<<<< HEAD
                    b.Property<string>("IdMovimiento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdLoteFk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdLoteFkNavigationIdLote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoMovimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdLoteFkNavigationIdLote");
=======
                    b.Property<int>("Id_movimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_movimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_lote")
                        .HasColumnType("int");

                    b.HasKey("Id_movimiento");
>>>>>>> 7f5891263b969f04d49c94ffaf374eeea2c2c7aa

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Sinmple.Models.Producto", b =>
                {
<<<<<<< HEAD
                    b.Property<string>("IdProducto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");
=======
                    b.Property<int>("Productos_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Productos_id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Productos_id");
>>>>>>> 7f5891263b969f04d49c94ffaf374eeea2c2c7aa

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Sinmple.Models.Usuario", b =>
                {
<<<<<<< HEAD
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Sinmple.Models.Cuenta", b =>
                {
                    b.HasOne("Sinmple.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Cuenta")
                        .HasForeignKey("IdUsuarioNavigationIdUsuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Sinmple.Models.Lote", b =>
                {
                    b.HasOne("Sinmple.Models.Producto", "IdProductoNavigation")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProductoNavigationIdProducto");

                    b.HasOne("Sinmple.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Lotes")
                        .HasForeignKey("IdUsuarioNavigationIdUsuario");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Sinmple.Models.MovimientosInventario", b =>
                {
                    b.HasOne("Sinmple.Models.Lote", "IdLoteFkNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdLoteFkNavigationIdLote");

                    b.Navigation("IdLoteFkNavigation");
                });

            modelBuilder.Entity("Sinmple.Models.Lote", b =>
                {
                    b.Navigation("MovimientoInventarios");
                });

            modelBuilder.Entity("Sinmple.Models.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Sinmple.Models.Usuario", b =>
                {
                    b.Navigation("Cuenta");

                    b.Navigation("Lotes");
                });
=======
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_usuario");

                    b.ToTable("Usuario");
                });
>>>>>>> 7f5891263b969f04d49c94ffaf374eeea2c2c7aa
#pragma warning restore 612, 618
        }
    }
}
